#ifndef VERSUSE_H
#define VERSUSE_H

/*
* in the land of defines everyone is sad
*/
#define VERSUSE_STRING_VERSION "v2.3"
#define VERSUSE_RES_VERSION 2,3,0,0
#define VERSUSE_RES_VERSION2 "2.3"
#define VERSUSE_STRING_CONFIG "versuse-conf.txt"

#define VERSUSE_MAIN 150
#define VERSUSE_ICON 151
//#define VERSUSE_ICO2 152

#define VERSUSE_BUTTON_WRITE 101
#define VERSUSE_EDIT_LEFTNAME 111
#define VERSUSE_EDIT_LEFTSCORE 113
#define VERSUSE_EDIT_RIGHTNAME 112
#define VERSUSE_EDIT_RIGHTSCORE 114
#define VERSUSE_EDIT_TEXTWIDTH 115

#define VERSUSE_OPTION_LEFT_L 121
#define VERSUSE_OPTION_LEFT_C 122
#define VERSUSE_OPTION_LEFT_R 123
#define VERSUSE_OPTION_RIGHT_L 124
#define VERSUSE_OPTION_RIGHT_C 125
#define VERSUSE_OPTION_RIGHT_R 126

#define VERSUSE_CBOX_BRACKET 141

#define VERSUSE_STATIC_GENERIC 130

#endif