#ifndef VERSUSE_H
#define VERSUSE_H

/*
* in the land of defines everyone is sad
*/
#define VERSUSE_STRING_VERSION "v3.1"
#define VERSUSE_RES_VERSION 3,1,0,0
#define VERSUSE_RES_VERSION2 "3.1"
#define VERSUSE_STRING_CONFIG "versuse-conf3.txt"

#define VERSUSE_MAIN 150
#define VERSUSE_ICON 151
//#define VERSUSE_ICO2 152

#define VERSUSE_BUTTON_WRITE 101
#define VERSUSE_EDIT_LEFTNAME 111
#define VERSUSE_EDIT_LEFTSCORE 113
#define VERSUSE_EDIT_RIGHTNAME 112
#define VERSUSE_EDIT_RIGHTSCORE 114
#define VERSUSE_EDIT_TEXTWIDTH 115

#define VERSUSE_OPTION_LEFT_L 121
#define VERSUSE_OPTION_LEFT_C 122
#define VERSUSE_OPTION_LEFT_R 123
#define VERSUSE_OPTION_RIGHT_L 124
#define VERSUSE_OPTION_RIGHT_C 125
#define VERSUSE_OPTION_RIGHT_R 126

#define VERSUSE_CBOX_BRACKET 141
#define VERSUSE_CBOX_LEFTNAME 142
#define VERSUSE_CBOX_LEFTSCORE 143
#define VERSUSE_CBOX_RIGHTNAME 144
#define VERSUSE_CBOX_RIGHTSCORE 145

#define VERSUSE_STATIC_GENERIC 130

#endif